// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: shopper-profile.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ShopperProfileServer {

  /// <summary>Holder for reflection information generated from shopper-profile.proto</summary>
  public static partial class ShopperProfileReflection {

    #region Descriptor
    /// <summary>File descriptor for shopper-profile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopperProfileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVzaG9wcGVyLXByb2ZpbGUucHJvdG8SB3Byb2ZpbGUiKgoVU2hvcHBlclBy",
            "b2ZpbGVSZXF1ZXN0EhEKCXNob3BwZXJJZBgBIAEoCSJJChZTaG9wcGVyUHJv",
            "ZmlsZVJlc3BvbnNlEi8KDnNob3BwZXJEZXRhaWxzGAEgASgLMhcucHJvZmls",
            "ZS5TaG9wcGVyRGV0YWlscyIxCg5TaG9wcGVyRGV0YWlscxIRCglzaG9wcGVy",
            "SWQYASABKAkSDAoEbmFtZRgCIAEoCTJmCg5TaG9wcGVyUHJvZmlsZRJUChFH",
            "ZXRTaG9wcGVyUHJvZmlsZRIeLnByb2ZpbGUuU2hvcHBlclByb2ZpbGVSZXF1",
            "ZXN0Gh8ucHJvZmlsZS5TaG9wcGVyUHJvZmlsZVJlc3BvbnNlQheqAhRTaG9w",
            "cGVyUHJvZmlsZVNlcnZlcmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ShopperProfileServer.ShopperProfileRequest), global::ShopperProfileServer.ShopperProfileRequest.Parser, new[]{ "ShopperId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ShopperProfileServer.ShopperProfileResponse), global::ShopperProfileServer.ShopperProfileResponse.Parser, new[]{ "ShopperDetails" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ShopperProfileServer.ShopperDetails), global::ShopperProfileServer.ShopperDetails.Parser, new[]{ "ShopperId", "Name" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The request message containing the user's name.
  /// </summary>
  public sealed partial class ShopperProfileRequest : pb::IMessage<ShopperProfileRequest> {
    private static readonly pb::MessageParser<ShopperProfileRequest> _parser = new pb::MessageParser<ShopperProfileRequest>(() => new ShopperProfileRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopperProfileRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ShopperProfileServer.ShopperProfileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileRequest(ShopperProfileRequest other) : this() {
      shopperId_ = other.shopperId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileRequest Clone() {
      return new ShopperProfileRequest(this);
    }

    /// <summary>Field number for the "shopperId" field.</summary>
    public const int ShopperIdFieldNumber = 1;
    private string shopperId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShopperId {
      get { return shopperId_; }
      set {
        shopperId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ShopperProfileRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ShopperProfileRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShopperId != other.ShopperId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ShopperId.Length != 0) hash ^= ShopperId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShopperId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ShopperId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShopperId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShopperId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ShopperProfileRequest other) {
      if (other == null) {
        return;
      }
      if (other.ShopperId.Length != 0) {
        ShopperId = other.ShopperId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ShopperId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// The response message containing the greetings.
  /// </summary>
  public sealed partial class ShopperProfileResponse : pb::IMessage<ShopperProfileResponse> {
    private static readonly pb::MessageParser<ShopperProfileResponse> _parser = new pb::MessageParser<ShopperProfileResponse>(() => new ShopperProfileResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopperProfileResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ShopperProfileServer.ShopperProfileReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileResponse(ShopperProfileResponse other) : this() {
      shopperDetails_ = other.shopperDetails_ != null ? other.shopperDetails_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperProfileResponse Clone() {
      return new ShopperProfileResponse(this);
    }

    /// <summary>Field number for the "shopperDetails" field.</summary>
    public const int ShopperDetailsFieldNumber = 1;
    private global::ShopperProfileServer.ShopperDetails shopperDetails_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ShopperProfileServer.ShopperDetails ShopperDetails {
      get { return shopperDetails_; }
      set {
        shopperDetails_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ShopperProfileResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ShopperProfileResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ShopperDetails, other.ShopperDetails)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (shopperDetails_ != null) hash ^= ShopperDetails.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (shopperDetails_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ShopperDetails);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (shopperDetails_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShopperDetails);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ShopperProfileResponse other) {
      if (other == null) {
        return;
      }
      if (other.shopperDetails_ != null) {
        if (shopperDetails_ == null) {
          ShopperDetails = new global::ShopperProfileServer.ShopperDetails();
        }
        ShopperDetails.MergeFrom(other.ShopperDetails);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (shopperDetails_ == null) {
              ShopperDetails = new global::ShopperProfileServer.ShopperDetails();
            }
            input.ReadMessage(ShopperDetails);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ShopperDetails : pb::IMessage<ShopperDetails> {
    private static readonly pb::MessageParser<ShopperDetails> _parser = new pb::MessageParser<ShopperDetails>(() => new ShopperDetails());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ShopperDetails> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ShopperProfileServer.ShopperProfileReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperDetails() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperDetails(ShopperDetails other) : this() {
      shopperId_ = other.shopperId_;
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ShopperDetails Clone() {
      return new ShopperDetails(this);
    }

    /// <summary>Field number for the "shopperId" field.</summary>
    public const int ShopperIdFieldNumber = 1;
    private string shopperId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ShopperId {
      get { return shopperId_; }
      set {
        shopperId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ShopperDetails);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ShopperDetails other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ShopperId != other.ShopperId) return false;
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ShopperId.Length != 0) hash ^= ShopperId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ShopperId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ShopperId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ShopperId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ShopperId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ShopperDetails other) {
      if (other == null) {
        return;
      }
      if (other.ShopperId.Length != 0) {
        ShopperId = other.ShopperId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ShopperId = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
